image: docker:latest
services:
  - docker:dind

stages:
  - build_jar
  - build_image
  - test
  - deploy

maven-build:
  image: maven:latest
  stage: build_jar
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: build_image
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"

maven-test:
  image: maven:latest
  stage: test
  script: "mvn test"

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - main
