image: docker:latest
services:
  - docker:dind

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.artifact.threads=50"

cache:
  paths:
    - .m2/repository/

stages:
  - build_jar
  - build_image
  - deploy

maven-build:
  image: maven:latest
  stage: build_jar
  script: "mvn package $MAVEN_CLI_OPTS $MAVEN_OPTS deploy -DskipTests -B"
  artifacts:
    paths:
      - target/*.jar
  only:
    - main

docker-build:
  stage: build_image
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  only:
    - main


deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - main
