spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 394823182792-1c2spaprgslrnpe97f6o7orgcecinqpi.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user